apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: playscapes
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - secretName: playscapes-com-tls
      hosts:
        - playscapespresents.com
  rules:
    - host: playscapespresents.com
      http:
        paths:
          - path: /admin
            backend:
              serviceName: playscapes-api
              servicePort: 80
          - path: /api
            backend:
              serviceName: playscapes-api
              servicePort: 80
          - path: /
            backend:
              serviceName: playscapes-nginx
              servicePort: 80
