# Generated by Django 3.2.3 on 2021-05-16 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('schedule_text', models.CharField(blank=True, max_length=200, null=True)),
                ('end_date', models.DateTimeField()),
                ('image_url', models.TextField()),
                ('event_type', models.CharField(choices=[('PP', 'Playscapes Presents'), ('NVC', 'Non-violent Communication')], max_length=3)),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type'], name='events_even_event_t_a87b5c_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['start_date'], name='events_even_start_d_d4b514_idx'),
        ),
    ]
