# Generated by Django 3.2.3 on 2021-05-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
