# Generated by Django 3.2.3 on 2021-05-17 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
    ]
